/*
===============================================================================
 DemoERPApi
 Script: Users_SeedData.sql

 Description
 -----------
 Inserts sample application users.

 NOTE:
 PasswordHash values below are placeholders for demonstration purposes.
 In a real application they should be generated by ASP.NET Identity or a
 secure password hashing mechanism.
===============================================================================
*/

DELETE FROM dbo.Users;
GO

SET IDENTITY_INSERT dbo.Users ON;
GO

INSERT INTO dbo.Users
(
    UserId,
    Username,
    PasswordHash,
    Role,
    CustomerID,
    IsActive
)
VALUES
(1, 'admin',    'HASHED_PASSWORD_ADMIN',    'Admin',    'CRM001', 1),
(2, 'owner',    'HASHED_PASSWORD_OWNER',    'Customer', 'CRM103', 1),
(3, 'customer', 'HASHED_PASSWORD_CUSTOMER', 'Customer', 'CRM104', 1),
(4, 'qauserA',  'HASHED_PASSWORD_QAUSERA',  'QA',       'CRM105', 1),
(5, 'qauserB',  'HASHED_PASSWORD_QAUSERB',  'QA',       'CRM106', 1),
(6, 'other',    'HASHED_PASSWORD_OTHER',    'Customer', 'CRM300', 1),
(7, 'owner2',   'HASHED_PASSWORD_OWNER2',   'Customer', 'CRM301', 1);
GO

SET IDENTITY_INSERT dbo.Users OFF;
GO
