/*
===============================================================================
 DemoERPApi
 Database Version: v1.0
 Script: V1_CreateDatabase.sql

 Description
 -----------
 Creates the initial database schema for DemoERPApi.

 Objects Created
 ---------------
 - Customers
 - Users
 - CustomerAccess

 Notes
 -----
 - This script creates schema objects only.
 - Seed data is stored in separate scripts under /SeedData.
===============================================================================
*/

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/*===========================================================================
    Customers
===========================================================================*/

IF OBJECT_ID('dbo.Customers', 'U') IS NOT NULL
    DROP TABLE dbo.Customers;
GO

CREATE TABLE dbo.Customers
(
    CRMCustomerID NVARCHAR(50) NOT NULL,
    FirstName     NVARCHAR(100) NOT NULL,
    LastName      NVARCHAR(100) NOT NULL,
    Email         NVARCHAR(255) NOT NULL,
    Phone         NVARCHAR(30) NULL,
    IsDeleted     BIT NOT NULL
        CONSTRAINT DF_Customers_IsDeleted DEFAULT (0),
    LastUpdated   DATETIME2 NOT NULL
        CONSTRAINT DF_Customers_LastUpdated DEFAULT SYSUTCDATETIME(),

    CONSTRAINT PK_Customers PRIMARY KEY (CRMCustomerID)
);
GO

CREATE UNIQUE INDEX IX_Customers_Email
ON dbo.Customers(Email);
GO

/*===========================================================================
    Users
===========================================================================*/

IF OBJECT_ID('dbo.Users', 'U') IS NOT NULL
    DROP TABLE dbo.Users;
GO

CREATE TABLE dbo.Users
(
    UserId       INT IDENTITY(1,1) NOT NULL,
    Username     NVARCHAR(100) NOT NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    Role         NVARCHAR(50) NOT NULL,
    CustomerID   NVARCHAR(50) NOT NULL,
    IsActive     BIT NOT NULL
        CONSTRAINT DF_Users_IsActive DEFAULT (1),

    CONSTRAINT PK_Users PRIMARY KEY (UserId),

    CONSTRAINT FK_Users_Customers
        FOREIGN KEY (CustomerID)
        REFERENCES dbo.Customers(CRMCustomerID)
);
GO

CREATE UNIQUE INDEX IX_Users_Username
ON dbo.Users(Username);
GO

/*===========================================================================
    CustomerAccess
===========================================================================*/

IF OBJECT_ID('dbo.CustomerAccess', 'U') IS NOT NULL
    DROP TABLE dbo.CustomerAccess;
GO

CREATE TABLE dbo.CustomerAccess
(
    Id            INT IDENTITY(1,1) NOT NULL,
    UserId        INT NOT NULL,
    CRMCustomerID NVARCHAR(50) NOT NULL,
    GrantedDate   DATETIME2 NOT NULL
        CONSTRAINT DF_CustomerAccess_GrantedDate DEFAULT SYSUTCDATETIME(),
    GrantedBy     NVARCHAR(100) NULL,

    CONSTRAINT PK_CustomerAccess PRIMARY KEY (Id),

    CONSTRAINT FK_CustomerAccess_Customers
        FOREIGN KEY (CRMCustomerID)
        REFERENCES dbo.Customers(CRMCustomerID),

    CONSTRAINT FK_CustomerAccess_Users
        FOREIGN KEY (UserId)
        REFERENCES dbo.Users(UserId)
);
GO

CREATE INDEX IX_CustomerAccess_Customer
ON dbo.CustomerAccess(CRMCustomerID);
GO

CREATE INDEX IX_CustomerAccess_User
ON dbo.CustomerAccess(UserId);
GO



/*
===============================================================================
 Create SyncLogs Table

 Stores execution results for customer synchronization operations.

 Example Operations:
   CREATE
   UPDATE
   DELETE
   RESTORE
   SYNC

 Example Status Values:
   SUCCESS
   WARNING
   FAILED

===============================================================================
*/

CREATE TABLE dbo.SyncLogs
(
    /*
    Unique identifier for each log record
    */
    LogId INT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_SyncLogs PRIMARY KEY,


    /*
    Customer identifier related to the operation.

    Example:
       CRM100
       CRM_TEST_001

    UNKNOWN is used when customer ID is unavailable.
    */
    CRMCustomerID NVARCHAR(200) NOT NULL,


    /*
    Business operation being executed.

    Examples:
       CREATE
       UPDATE
       DELETE
       RESTORE
       SYNC
    */
    Operation NVARCHAR(80) NOT NULL,


    /*
    Execution result.

    Expected Values:
       SUCCESS
       WARNING
       FAILED
    */
    Status NVARCHAR(80) NOT NULL,


    /*
    Additional execution information.

    Examples:
       Customer created successfully
       Duplicate customer submitted
       CustomerID required
       Database timeout
    */
    Message NVARCHAR(2000) NULL,


    /*
    User or service account executing the operation.

    Examples:
       admin
       owner1
       qauserB
       Unknown
    */
    Username NVARCHAR(400) NULL,


    /*
    Unique request identifier generated by ASP.NET Core.

    Used for:
       - API request tracing
       - Troubleshooting distributed requests
       - Correlating logs
    */
    RequestId NVARCHAR(400) NULL,


    /*
    Timestamp when operation was executed.
    */
    CreatedDate DATETIME2 NOT NULL
        CONSTRAINT DF_SyncLogs_CreatedDate
        DEFAULT SYSUTCDATETIME(),


    /*
    Total execution time in milliseconds.

    Used for:
       - Performance monitoring
       - API response analysis
       - Identifying slow operations
    */
    ExecutionTimeMs INT NULL
);
GO

PRINT 'DemoERPApi v1.0 database schema created successfully.';
GO




CREATE TABLE DataQualityScores
(
    Id INT IDENTITY PRIMARY KEY,

    CRMCustomerID VARCHAR(50),

    Score INT,

    MissingFields INT,

    ValidationErrors INT,

    CheckedDate DATETIME,

    RequestId VARCHAR(100)
)
