CREATE TABLE Customer(
CustomerID INT IDENTITY PRIMARY KEY,
CRMCustomerID VARCHAR(30) UNIQUE,
FirstName VARCHAR(50),
LastName VARCHAR(50),
Email VARCHAR(100),
Phone VARCHAR(20),
LastUpdated DATETIME,
IsDeleted BIT DEFAULT 0
);
